In [1]:
import pickle 
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
pickled_model = pickle.load(open('fuelprice_model.pkl', 'rb'))

In [3]:
data =  [77,  1444454.80, 0 , 44.44 ,  216.886655 , 9.287, 44, 11, 2016 ]

In [4]:
data_2d = np.array(data).reshape(1,-1)

In [5]:
pickled_model.predict(data_2d)

array([3.4376395], dtype=float32)

In [6]:
sample = [3 , 348895.98 , 0 , 71.64 , 215.17839 , 7.564 , 39 ,10, 2010]
#actual is 2.725

In [7]:
sample_2d = np.array(sample).reshape(1,-1)


In [8]:
pickled_model.predict(sample_2d)

array([2.5864315], dtype=float32)

In [9]:
pickled_ada = pickle.load(open('fuelprice_ada_model.pkl', 'rb'))

In [10]:
pickled_ada.predict(data_2d)

array([3.492])

In [11]:
pickled_ada.predict(sample_2d)

array([2.603])

In [12]:
sample_2 = [3 , 443557.65 , 0 , 72.74 , 226.7210356 , 6.034 , 37 , 10 , 2012]
#actual 3.617

In [13]:
sample2_2d = np.array(sample_2).reshape(1,-1)

In [14]:
pickled_ada.predict(sample2_2d)

array([3.666])

In [15]:
pickled_model.predict(sample2_2d)

array([3.5446813], dtype=float32)

In [16]:
pickled_rf = pickle.load(open('fuelprice_rf_model.pkl', 'rb'))

In [17]:
pickled_rf.predict(sample_2d)

array([2.60852])

In [18]:
pickled_rf.predict(sample2_2d)

array([3.66716])